name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    tags:
      - 'v*'

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

  del_runs:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    permissions:
      actions: write
      contents: write
    steps:
      - name: remove preview workflow runs
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: delete-workflow-runs
          client-payload: '{"days": 0, "minimum_runs": 6, "pattern": "Vercel Preview Deployment"}'

      - name: remove delete workflow runs
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: delete-workflow-runs
          client-payload: '{"days": 0, "minimum_runs": 0, "workflow_pattern": "Delete Workflow Runs"}'
